apiVersion: v1
kind: Service
metadata:
  name: crud-app-nodeport-svc
spec:
  type: NodePort
  selector:
    app: crud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30909
