apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
