apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-chat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-chat-app
  template:
    metadata:
      labels:
        app: react-chat-app
    spec:
      containers:
        - name: react-chat-app
          image: diaaqassem1/reactapp:v2.9
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "812m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-chat-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-chat-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
