apiVersion: v1
kind: Service
metadata:
  name: mongodb-chat-app-service-cluster-ip
spec:
  selector:
    app: mongodb-chat-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
