apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-chat-app-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/diaa/chat-app/DB/mongo-data
