apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-svc
spec:
  selector:
    app: chat-app
  ports:
    - name: app
      port: 5000
      targetPort: 5000
    - name: gateway
      port: 5001
      targetPort: 5001
  type: ClusterIP
