apiVersion: apps/v1
kind: Deployment
metadata:
  name: xo-app-deployment
  labels:
    app: xo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xo-app
  template:
    metadata:
      labels:
        app: xo-app
    spec:
      containers:
      - name: xo-app
        image: karimanmahmoud/xo-app
        ports:
        - containerPort: 80
